CREATE DATABASE vigilate
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE ROLE vigilate WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
	
GRANT ALL ON DATABASE vigilate TO vigilate;

ALTER ROLE vigilate
	PASSWORD 'Password1234$';